### PR TITLE
Fixed 1.14

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
Everything seems to work, but I didn't test too much

### CODE REVIEW

**Review by RoboMWM — APPROVED** [review]
Looks good, but seems to be 1.14-specific though? Looks like nothing much changed other than new Material enums and using the view to get the title.

Does getting the inventory name not work on 1.14 despite the plugin written on `api-version: 1.13`?

**Comment by ThexXTURBOXx** [comment]
Yes, this is 1.14-specific.
If you want this to be compatible with 1.13, too, I could try to implement NMS.
Getting inventory names was deprecated in 1.13 already and was removed in 1.14 im favor of Getting the names of ImventoryViews.

**Comment by RoboMWM** [comment]
Ok, so this plugin does not work on 1.14 (without this PR)?

No need for NMS, thanks though.

**Comment by ThexXTURBOXx** [comment]
Yes, there will be random crashes in 1.14.
E.g. it cant find the Material "SIGN" or a NoSuchMethodException when trying to get an inventory's Name.

**Comment by RoboMWM** [comment]
How would this cause "random" crashes? If anything it should just be throwing exceptions (which do not crash the server).

I would imagine though that it should convert `api-version: 1.13` enums to 1.14? Or is that not the case.

**Comment by ThexXTURBOXx** [comment]
I just call them "random crashes", ofc you are right. The plugin crashes, That's why I call them like that.
At least for me, the plugin needed those changes. I will test a little bit further and will report back (could take a while, I won't be home for a little bit)

**Comment by RoboMWM** [comment]
@ThexXTURBOXx I'm not sure how this worked without `api-version: 1.14`

**Comment by ThexXTURBOXx** [comment]
Why?

**Comment by RoboMWM** [comment]
You're using the new 1.14 signs

**Comment by ThexXTURBOXx** [comment]
The whole api Version thing is a good concept, but the Server Doesnt seem to really care about that yet... Maybe this gets added later on

**Comment by RoboMWM** [comment]
Idk what you're talking about, the server definitely does care about it... Idk how the plugin is going to check for specific types of wood signs on 1.13...

**Comment by ThexXTURBOXx** [comment]
As is stated in my first comment here, this breaks 1.13 compatibility.
The api-Version Doesnt change, how the api looks like in runtime. If you think about it, this makes definetly sense.
You can't just Set the api Version to 1.13 and use, e.g. The old TravelAgent (which got removed in 1.14).
Changing the api-Version doesn't change, how the classes of the bukkit/spigot api Look like. It's more or less just like the "targetSdkVersion" for Android Apps, which just specifies, on which versions the build got tested.

**Comment by ThexXTURBOXx** [comment]
I dont really know, but right now it definetly behaves like that. Not only I can report that behavior.
It could be, that further changes/additions/fixes may come in a future Update, but for now, this is broken

**Comment by RoboMWM** [comment]
This isn't how it behaves with e.g. legacy materials. If `api-version` isn't present it'll assume it's a pre-1.13 plugin and attempt to convert Materials to 1.13-equivalents (or whatever server version it's on). I guess it's not doing this conversion if the plugin is using 1.14 API on a 1.14 server, as long as `api-version` is present? Doesn't seem md-5 documented this in any of his recent spigot posts.

Either way, 1.14 should be specified anyways if it isn't backwards-compatible.

**Pull request merged**
