### PR TITLE
Update to Minecraft v1.21

### PR DESCRIPTION
**Pull request by ChristopherHaws**

### CODE REVIEW

**Comment by RoboMWM** [comment]
wowo that's quite the changes

**Comment by RoboMWM** [comment]
if you're interested in maintaining, I can provide access to the bukkitdev page and optionally this repo, otherwise have fun!

**Comment by ChristopherHaws** [comment]
@RoboMWM Hey! Totally up to you, my bukkitdev name is chaws314. I am not super active in maintaining it right now, but I do keep it up to date with major versions since one of the SMP servers I play on uses it and needed some bugs fixed and wanted a few additional features added.

**Comment by RoboMWM** [comment]
cool sounds good! I'll add you to the project. Let me know if there are any other things you'd like to change besides uploading new releases.

**Pull request closed without merging**
